name: build-checksum-test
on:
  workflow_dispatch:

jobs:
  build_container:
    name: main
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Buildah Build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: myimage
          tags: |
            ${{ github.sha }}